name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We'd love to hear your ideas for improving TalkType.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem would this feature solve? What are you trying to do?
      placeholder: "I find it difficult to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: "It would be great if TalkType could..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you tried any workarounds? Are there other ways to solve this?

  - type: dropdown
    id: desktop
    attributes:
      label: Desktop Environment (if relevant)
      description: Is this feature specific to a desktop environment?
      options:
        - All desktops
        - GNOME
        - KDE Plasma
        - XFCE
        - Other

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information, screenshots, or examples that would help explain your idea
