"""Stop the dictation hotkeys reaching the focused app on KDE.

The service reads the keyboard with evdev, underneath the desktop, so it sees F8
at the same moment KWin does and cannot stop KWin passing the press on. The
keyboard grab goes on only after the press, which is already on its way to the
focused window. Terminals turn F8 into an escape sequence ending in "~", and the
shell prints the "~". The toggle key (F9) is never grabbed at all, so it leaked
on press and release alike.

KWin hands a key to an app only if it isn't a global shortcut. So while the
service runs, a small KWin script registers the hotkeys as shortcuts that do
nothing. KWin swallows the key; evdev still sees the raw press and release, so
recording works exactly as before.

Proven against Plasma 6.7.4 on Wayland before this module was written, with a
window logging every key it received:
  * shortcut registered from a script loaded over D-Bus: the window got neither
    the press nor the release, and the next key arrived normally;
  * script unloaded: the key reached the window again. A shortcut left behind
    in kglobalshortcutsrc with no script behind it does not swallow anything.
  * Re-registering a name with a different key keeps the OLD key: kglobalaccel
    prefers what it saved over the new default. Hence the key is part of each
    shortcut's name, and release() unregisters them all, so a changed hotkey is
    always registered fresh.

The service owns this, not the tray: the auto-timeout makes the service exit,
and with dictation off F8 should be an ordinary key again. Every stop path goes
through service_launcher.stop_dictation_service(), which releases; the tray
releases too if the service dies without that (crash, SIGKILL).

Nothing here may be fatal. Failing to claim a key costs the "~" fix; it must
never cost dictation.
"""

import os

from . import desktop_detect
from .kwin_focus import (KWIN_SCRIPTING_INTERFACE, KWIN_SCRIPTING_PATH,
                         KWIN_SERVICE, load_and_start)
from .logger import setup_logger

# setup_logger, not logging.getLogger: only it reaches talktype.log, and the
# "KDE already uses F8" warning is no use if the user can't find it.
logger = setup_logger(__name__)

SCRIPT_PLUGIN_NAME = "talktype-hotkeys"

# Every shortcut we register starts with this, which is how release() finds
# them, including ones left by an older run with a different hotkey.
SHORTCUT_PREFIX = "talktype-"

KGLOBALACCEL_SERVICE = "org.kde.kglobalaccel"
KGLOBALACCEL_PATH = "/kglobalaccel"
KGLOBALACCEL_INTERFACE = "org.kde.KGlobalAccel"
KWIN_COMPONENT_PATH = "/component/kwin"
KGLOBALACCEL_COMPONENT_INTERFACE = "org.kde.kglobalaccel.Component"

# KWin answers in milliseconds; this only bounds a wedged compositor.
_DBUS_TIMEOUT_S = 3.0

# TalkType's modifier names -> Qt's.
_QT_MODIFIERS = {"CTRL": "Ctrl", "SHIFT": "Shift", "ALT": "Alt", "SUPER": "Meta"}
_FKEYS = {f"F{i}" for i in range(1, 13)}


def qt_key_sequence(name):
    """TalkType's hotkey name ("F8", "Ctrl+Alt+V") as a Qt key sequence, or None.

    A bare key is only claimed if it's an F-key. Claiming a bare letter would
    stop the user typing that letter anywhere while the service runs.
    """
    if not name or not name.strip():
        return None
    parts = [p.strip().upper() for p in name.split("+")]
    key = parts[-1]
    if not (key in _FKEYS or (len(key) == 1 and "A" <= key <= "Z")):
        return None
    mods = []
    for part in parts[:-1]:
        if part not in _QT_MODIFIERS:
            return None
        mods.append(_QT_MODIFIERS[part])
    if not mods and key not in _FKEYS:
        return None
    return "+".join(mods + [key])


def wanted_shortcuts(cfg):
    """[(shortcut name, description, Qt key)] for the hotkeys in *cfg*."""
    roles = (
        ("hold", "hold to talk", getattr(cfg, "hotkey", "")),
        ("toggle", "tap to start and stop", getattr(cfg, "toggle_hotkey", "")),
        ("voice-commands", "voice commands", getattr(cfg, "voice_commands_hotkey", "")),
    )
    out, seen = [], set()
    for role, what, name in roles:
        key = qt_key_sequence(name)
        if key and key not in seen:   # one key can only be registered once
            seen.add(key)
            out.append((f"{SHORTCUT_PREFIX}{role}-{key}",
                        f"TalkType: {what} ({key}), managed by TalkType", key))
    return out


def build_script(shortcuts) -> str:
    """The KWin script: register each hotkey with a callback that does nothing.

    The keys come from qt_key_sequence (F-keys, letters, modifier names) and
    the names/descriptions are built from them, so none can contain a quote.
    """
    lines = ["// Generated by TalkType. Keeps the dictation hotkeys out of the",
             "// focused app while the service runs. Rewritten at every start."]
    for name, text, key in shortcuts:
        lines.append(f'registerShortcut("{name}", "{text}", "{key}", function() {{}});')
    return "\n".join(lines) + "\n"


def script_path() -> str:
    from .config import get_data_dir

    return os.path.join(get_data_dir(), "kwin", "talktype-hotkeys.js")


def should_claim() -> bool:
    """KDE outside a Flatpak. The Flatpak gets its keys from the GlobalShortcuts
    portal, where the desktop already owns them, and has no KWin to talk to."""
    if os.environ.get("FLATPAK_ID"):
        return False
    return desktop_detect.get_desktop_environment() == "kde"


def session_bus():
    """A .call(method, *args) shim over KWin scripting and kglobalaccel.

    Imported lazily so this module stays importable (and testable) without
    dbus-python.
    """
    import dbus

    bus = dbus.SessionBus()

    class _Bus:
        def call(self, method, *args):
            t = {"timeout": _DBUS_TIMEOUT_S}
            if method in ("loadScript", "unloadScript", "start"):
                obj = bus.get_object(KWIN_SERVICE, KWIN_SCRIPTING_PATH)
                # loadScript is overloaded; see kwin_focus.session_bus.
                sig = {"loadScript": "ss", "unloadScript": "s", "start": ""}[method]
                return getattr(obj, method)(*args, dbus_interface=KWIN_SCRIPTING_INTERFACE,
                                            signature=sig, **t)
            if method == "unregister":
                obj = bus.get_object(KGLOBALACCEL_SERVICE, KGLOBALACCEL_PATH)
                return obj.unregister(*args, dbus_interface=KGLOBALACCEL_INTERFACE, **t)
            if method in ("shortcutNames", "allShortcutInfos"):
                obj = bus.get_object(KGLOBALACCEL_SERVICE, KWIN_COMPONENT_PATH)
                return getattr(obj, method)(dbus_interface=KGLOBALACCEL_COMPONENT_INTERFACE, **t)
            raise ValueError(method)

    return _Bus()


def _unregister_ours(bus) -> None:
    """Remove every talktype-* shortcut from KWin's component."""
    try:
        names = [str(n) for n in bus.call("shortcutNames")]
    except Exception as e:
        logger.debug(f"Could not list KWin shortcuts: {e}")
        return
    for name in names:
        if name.startswith(SHORTCUT_PREFIX):
            try:
                bus.call("unregister", "kwin", name)
            except Exception as e:
                logger.debug(f"Could not unregister KWin shortcut {name}: {e}")


def _log_refused(bus, shortcuts) -> None:
    """Say which hotkeys KDE would not give us (already another shortcut's)."""
    try:
        infos = bus.call("allShortcutInfos")
        # (name, text, component, component name, context, context name,
        #  keys, default keys), as read back from Plasma 6.7.4.
        got = {str(i[0]): list(i[6]) for i in infos}
    except Exception as e:
        logger.debug(f"Could not read back KWin shortcuts: {e}")
        return
    for name, _text, key in shortcuts:
        if not got.get(name):
            logger.warning(
                f"KDE already uses {key} for another shortcut, so it will still "
                f"reach the focused app as well as starting dictation")


def claim(cfg, bus=None) -> bool:
    """Register *cfg*'s hotkeys with KWin. True if the script is running.

    Safe to call again after a hotkey change: it releases first, so the new
    keys are registered fresh rather than kglobalaccel keeping the old ones.
    """
    if not should_claim():
        return False
    shortcuts = wanted_shortcuts(cfg)
    try:
        bus = bus or session_bus()
    except Exception as e:
        logger.debug(f"No session bus for KWin hotkeys: {e}")
        return False
    release(bus)
    if not shortcuts:
        return False
    try:
        path = script_path()
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(build_script(shortcuts))
        load_and_start(bus, path, SCRIPT_PLUGIN_NAME)
    except Exception as e:
        logger.warning(f"Could not register the hotkeys with KWin: {e}")
        return False
    _log_refused(bus, shortcuts)
    logger.info("KWin now holds the hotkeys back from the focused app: "
                + ", ".join(k for _n, _t, k in shortcuts))
    return True


def release(bus=None) -> None:
    """Unload the script and forget our shortcuts. Never raises: quit path."""
    if not should_claim():
        return
    try:
        bus = bus or session_bus()
    except Exception as e:
        logger.debug(f"No session bus for KWin hotkeys: {e}")
        return
    try:
        bus.call("unloadScript", SCRIPT_PLUGIN_NAME)
    except Exception as e:
        logger.debug(f"Could not unload the KWin hotkey script: {e}")
    _unregister_ours(bus)
