"""Report the focused window to TalkType on KDE, the way the extension does on GNOME.

Two features key off which window has focus: paste sends Ctrl+Shift+V to
terminals (they treat plain Ctrl+V as readline's quoted-insert and show nothing),
and Electron apps that swallow synthetic paste are routed to a typing fallback.
Both read one cache, filled by SetFocusedWindowClass.

Until now the only writer was the GNOME Shell extension, so on KDE the cache was
empty forever and every paste used Ctrl+V. Dictating into a terminal put nothing
on screen while TalkType logged success and played the ready beep.

KWin has no D-Bus property for the active window — queryWindowInfo() asks the
user to click one, and getWindowInfo() needs a UUID you do not have. The usable
route is a KWin script: it runs inside KWin, can read workspace.activeWindow, and
can call back out over D-Bus. So this loads a small script that pushes
resourceClass into the same method the extension calls, leaving everything
downstream untouched.

Proven against Plasma 6.7.4 on Wayland before this module was written: with the
script loaded, the cache tracked com.anthropic.Claude -> zenity -> back as focus
moved.

Nothing here may be fatal. A missing KWin, a refused call or an unwritable data
directory costs the paste hint; it must never cost the tray.
"""

import os

from . import desktop_detect
from .dbus_service import DBUS_INTERFACE, DBUS_NAME, DBUS_PATH
from .logger import setup_logger

# setup_logger: a plain getLogger never reaches talktype.log, which hid this
# module's warnings entirely.
logger = setup_logger(__name__)

# KWin identifies loaded scripts by this name; unloading uses it too.
SCRIPT_PLUGIN_NAME = "talktype-focus"

KWIN_SERVICE = "org.kde.KWin"
KWIN_SCRIPTING_PATH = "/Scripting"
KWIN_SCRIPTING_INTERFACE = "org.kde.kwin.Scripting"


def script_path() -> str:
    """Where the KWin script is written.

    It has to be a real file: loadScript takes a path, and KWin reads it. The
    data directory is stable across runs, unlike an AppImage's mount point.
    """
    from .config import get_data_dir

    return os.path.join(get_data_dir(), "kwin", "talktype-focus.js")


def build_script() -> str:
    """The KWin script source.

    Reports on every focus change AND once at load, so the hint is right
    immediately rather than only after the user switches windows.
    """
    return f"""// Generated by TalkType. Reports the focused window so paste can
// choose Ctrl+Shift+V for terminals. Safe to delete; it is rewritten at startup.
function talktypeReport(w) {{
    var cls = (w && w.resourceClass) ? String(w.resourceClass) : "";
    callDBus("{DBUS_NAME}",
             "{DBUS_PATH}",
             "{DBUS_INTERFACE}",
             "SetFocusedWindowClass",
             cls);
}}

if (workspace.windowActivated) {{
    workspace.windowActivated.connect(talktypeReport);
}}

talktypeReport(workspace.activeWindow);
"""


def session_bus():
    """A .call(method, *args) shim over KWin's Scripting interface.

    dbus is imported here rather than at module scope so this module stays
    importable (and testable) without dbus-python present.
    """
    import dbus

    bus = dbus.SessionBus()

    # KWin publishes loadScript twice — (path) and (path, pluginName). Without
    # an explicit signature dbus-python matches the one-argument overload and
    # rejects the call, so the plugin name (which unloadScript needs later) has
    # to be spelled out here.
    signatures = {"loadScript": "ss", "unloadScript": "s"}

    class _KWinBus:
        def call(self, method, *args):
            obj = bus.get_object(KWIN_SERVICE, KWIN_SCRIPTING_PATH)
            kwargs = {"dbus_interface": KWIN_SCRIPTING_INTERFACE}
            if method in signatures:
                kwargs["signature"] = signatures[method]
            return getattr(obj, method)(*args, **kwargs)

    return _KWinBus()


def load_and_start(bus, path, plugin_name) -> None:
    """Load a script file into KWin and start it. Raises if KWin refuses.

    Started with Scripting.start(), which runs every loaded script that isn't
    running yet, NOT with run() on /Scripting/Script<id>. KWin numbers a new
    script by how many are loaded (scripts.size()), so after an unload a new
    script can get the number of one still loaded. Its D-Bus object then fails
    to register and run() starts the other script instead. That happened as
    soon as TalkType had two scripts: after a tray restart the focus script
    loaded but never ran, every paste fell back to Ctrl+V, and a terminal
    showed "^V". start() skips scripts already running, so it is safe to call
    for one new script.
    """
    script_id = bus.call("loadScript", path, plugin_name)
    if int(script_id) < 0:
        # -1: a script by this name is still loaded (the unload hadn't landed).
        raise RuntimeError(f"KWin already has a script named {plugin_name}")
    bus.call("start")


def should_provide() -> bool:
    """Whether this desktop needs us to report focus.

    GNOME is excluded deliberately: its extension already writes the same cache,
    and two writers would race each other for no gain.
    """
    return desktop_detect.get_desktop_environment() == "kde"


def _write_script() -> str:
    path = script_path()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(build_script())
    return path


def start(bus) -> bool:
    """Load the focus reporter into KWin. True when it is running.

    *bus* is a small caller-supplied shim with .call(method, *args) so the
    D-Bus plumbing stays testable and this module stays import-safe without
    dbus-python present.
    """
    if bus is None or not should_provide():
        return False

    try:
        path = _write_script()
    except Exception as e:
        logger.warning(f"Could not write the KWin focus script: {e}")
        return False

    try:
        # KWin keeps scripts loaded across tray restarts, and loading a second
        # copy would report every focus change twice.
        bus.call("unloadScript", SCRIPT_PLUGIN_NAME)
    except Exception as e:
        logger.debug(f"No previous KWin focus script to unload: {e}")

    try:
        load_and_start(bus, path, SCRIPT_PLUGIN_NAME)
    except Exception as e:
        logger.warning(f"Could not load the KWin focus script: {e}")
        return False

    logger.info("KWin focus reporter loaded; terminal paste detection is active")
    return True


def stop(bus) -> None:
    """Unload the reporter. Never raises — this runs on the quit path."""
    if bus is None:
        return
    try:
        bus.call("unloadScript", SCRIPT_PLUGIN_NAME)
    except Exception as e:
        logger.debug(f"Could not unload the KWin focus script: {e}")
