#!/bin/sh
SELF=$(readlink -f "$0")
HERE=${SELF%/*}
export PATH="${HERE}/usr/bin:${PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH}"
export PYTHONPATH="${HERE}/usr/src:${HERE}/usr/lib/python3.10/site-packages"
export GI_TYPELIB_PATH="${HERE}/usr/lib/girepository-1.0"
export PYTHONHOME="${HERE}/usr"
cd "$HOME"
if [ "$1" = "prefs" ]; then
    exec "${HERE}/usr/bin/python3" -m talktype.prefs
else
    exec "${HERE}/usr/bin/python3" -m talktype.tray "$@"
fi
